# Generated by Django 3.2.5 on 2021-09-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("romaji_title", models.CharField(max_length=200)),
                ("feed_url", models.URLField()),
                ("episode_offset", models.IntegerField(default=0)),
                ("anilist_id", models.IntegerField()),
            ],
        ),
    ]
