# Generated by Django 3.2.5 on 2021-09-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animefs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="episode_extracting_regex",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="series",
            name="feed_url",
            field=models.URLField(blank=True),
        ),
    ]
